### ISSUE TITLE
please make sure to invalidate branches list in zeroCI

### ISSUE THREAD

**Issue by xmonader** [AhmedHanafy725/0-CI#10]
branches in zeroCI doesn't reflect the true state. there're some very old branches zeroCI that been merged or removed

**Comment by 0xIslamTaha** [comment]
shouldn't we keep the history?

**Comment by rkhamis** [comment]
I think a deleted branch doesn't really need much history.
Or at least it can be categorized under `deleted branches`. It's now a little hard to find the current status across active branches

**Comment by AhmedHanafy725** [comment]
> I think a deleted branch doesn't really need much history.
> Or at least it can be categorized under `deleted branches`. It's now a little hard to find the current status across active branches

Done on 8fd243ce28c0b651904ce0b613107ae5dbfeb881
![image](https://user-images.githubusercontent.com/41957921/72983392-d5b05980-3de9-11ea-931d-325d1503ebfe.png)
