### ISSUE TITLE
when localhost:port is used as domin, telegram doesn't get a message 

### ISSUE THREAD

**Issue by john-kheir** [AhmedHanafy725/0-CI#29]
## Scenario
1- Deploy zeroci on a local container
2- Add `domain` in config.toml as `localhost:outside_port` --> This domain is used for target_url and telegram 
    .. step 2 to make sure u can reach the target url from github or gitea
3- check if u received a message on telegram 

## Actual Result
no message has been received on telegram 

## Expected result 
A message should be send with the commit and the results, etc

Note: if u put the domain as 0.0.0.0:container_local_port, the message will be send to telegram

**Comment by AhmedHanafy725** [comment]
This happens because domain should contain `.` to be a real domain.
