### ISSUE TITLE
More validation on initial config

### ISSUE THREAD

**Issue by AhmedHanafy725** [AhmedHanafy725/0-CI#45]
In case of a user entered a valid type and non-valid content, zeroci will crash and maybe can't start again, or even run with error, and the user won't know what is wrong.

extend to #35

**Comment by AhmedHanafy725** [comment]
Done on backend the flow will be:

- Ask for zeroci domain, vcs (version control system) host and vcs token.
- Make sure that vcs is reachable.
- Ask for the organization or username on vcs that you want to use zeroci for them.
- Return a list of all repositories under this organization or username.
- Now user can select between them.
- Create web hook for each repository selected (it will fail if the vcs token is invalid).
- Ask for telegram bot and chat ID.
- Send a message to chat ID in case of no error.
- Finally you can apply these changes.

**Comment by AhmedHanafy725** [comment]
## New apis
(**Note:** all required variables in POST requests should be json.)
### `/api/vcs_config`
**GET:** return the values of `domain`, `vcs_host` and `vcs_token`.
**POST:** requires the values  of `domain`, `vcs_host` and `vcs_token`.

### `/api/repos_config`
**GET:** return list of repositories zeroci is working on.
**POST:** require list of repositories need zeroci to be working on.

### `/api/repos_config?username<username>`:
**GET:** return the repositories owned by this `username`.

### `/api/repos_config?org_name=<org_name>`:
**GET:** return the repositories in this `org_name`.

### `/api/telegram_config`
**GET:** return telegram `chat_id` and `bot_token`
**POST:** requires telegram `chat_id` and `bot_token`

### `/api/users`
**GET:** return users and admins zeroci.
**POST:** requires `user` or `admin`.
**DELETE:** requires `user` or `admin`

### `/api/apply_config`
**POST** to apply the config.

**Comment by samaradel** [comment]
when VCS token is invalid the server doesn't return an error response

**Comment by samaradel** [comment]
response errors come with status code 200

**Comment by AhmedHanafy725** [comment]
> response errors come with status code 200

This happens because there is issue in `Response` method https://stackoverflow.com/questions/16638117/setting-http-status-code-in-bottle/16641525
So I will use `HTTPResponse` instead.

**Comment by samaradel** [comment]
for users part https://github.com/threefoldtech/zeroCI/issues/57

**Comment by AhmedHanafy725** [comment]
**Verified**

![image](https://user-images.githubusercontent.com/41957921/89403181-38c76500-d718-11ea-8671-5011c9000dc4.png)
