### ISSUE TITLE
usecase 1: building publishing tools

### ISSUE THREAD

**Issue by despiegk** [AhmedHanafy725/0-CI#50]
- build the publ tool
- start in a container
- check from other container that the wiki page is there
- publish the binary on webserver as part of zeroci

which means we can offer people to always have the latest binaries available which passed some tests

**Comment by AhmedHanafy725** [comment]
1- Handling the bin in frontend and telegram is done.
2- Copy bin from testing container to the zeroci host is done with kubernetes python client, but it didn't work as can't use `cat` with binary files and also can't use `tar` in case of `tar` is not in the testing container and it may be corrupted while reading and writing.
So I will try with volume mount to copy the file.

**Comment by AhmedHanafy725** [comment]
Couldn't build the publishing tools binary https://github.com/threefoldfoundation/publishingtools/issues/148

**Comment by AhmedHanafy725** [comment]
1- Mount the location of the binary works fine and now can get the binary and store it.
2- For `alpine` container there is no `bash` bin, so zeroci will not be able to run the commands in config file. Solution: add in config file `shell_bin` under `prerequisites` in case of bash not used.
3- cloning issue #53

**Comment by AhmedHanafy725** [comment]
> 1- Mount the location of the binary works fine and now can get the binary and store it.
> 2- For `apline` container this is no `bash` bin, so zeroci will not be able to run the commands in config file. Solution: add in config file `shell_bin` under `prerequisites` in case of bash not used.
> 3- cloning issue #53

These solutions is done.

Next step: Supporting mutli jobs (serial for now).

**Comment by AhmedHanafy725** [comment]
Can't build publishing tool bin https://github.com/crystaluniverse/publishingtools/issues/152
- Adding memory limit for containers.
