### ISSUE TITLE
migrate to jsng

### ISSUE THREAD

**Issue by despiegk** [AhmedHanafy725/0-CI#51]

**Comment by AhmedHanafy725** [comment]
- models migration is done.
- porting 3bot login is done.
- need to be tested in k8s cluster, so need to create image first (https://github.com/threefoldtech/zeroCI/issues/25)

**Comment by AhmedHanafy725** [comment]
Can't get and view the result in frontend after the object is updated in a worker.
https://github.com/threefoldtech/js-ng/issues/378

**Comment by AhmedHanafy725** [comment]
Done and current deployment is working on https://zeroci.grid.tf
