### ISSUE TITLE
support for neph

### ISSUE THREAD

**Issue by despiegk** [AhmedHanafy725/0-CI#52]
- neph runs in tmux
- use CT (Crystal Tools & DO)
- neph logs can be seen from UI
- neph main process can be seen from UI

## support for CT

- git pull/push
- tmux mgmt
- docker: still to do

**Comment by AhmedHanafy725** [comment]
Building `neph` binary and add it to the helper image to be injected in the testing container.

**Comment by AhmedHanafy725** [comment]
- Main neph process can be streamed from UI and also can be seen in final result.
- Jobs' logs can be seen only after the main process is done in the final result.

PR: #65

**Comment by AhmedHanafy725** [comment]
Needs #66 for support streamed logs for neph jobs.

**Comment by AhmedHanafy725** [comment]
### websockets that supports neph's jobs to be streamed:

`/websocket/neph_jobs/<id>`: to get neph jobs IDs that should be streamed. (id: Run ID for zeroci)

`/websocket/neph_logs/<neph_id>`: use the IDs from the previous api to get the logs.

**Comment by AhmedHanafy725** [comment]
How to use https://github.com/threefoldtech/zeroCI#neph

![image](https://user-images.githubusercontent.com/41957921/89402647-7972ae80-d717-11ea-9980-c12d62917732.png)
