### ISSUE TITLE
Add user management page 

### ISSUE THREAD

**Issue by samaradel** [AhmedHanafy725/0-CI#57]
### `/api/users`
**GET:** return users and admins zeroci.
**POST:** requires `user` or `admin`.
**DELETE:** requires `user` or `admin`

**Comment by AhmedHanafy725** [comment]
**Verified**
Only admins can access it.

![image](https://user-images.githubusercontent.com/41957921/89401959-66abaa00-d716-11ea-943c-5686d2114ff7.png)
